# Generated by Django 5.2 on 2025-05-03 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('preferred_store', models.CharField(blank=True, choices=[('monkey_planet', 'Monkey Planet'), ('baul_del_enano', 'Baul del Enano'), ('dragonscave', 'Dragonscave'), ('camelot', 'Camelot'), ('tiempo_de_juegos', 'Tiempo de Juegos')], max_length=20, null=True)),
                ('transaction_preference', models.CharField(blank=True, choices=[('buy_only', 'Solo Compra'), ('sell_only', 'Solo Venta'), ('buy_and_sell', 'Compra y Venta')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
