# Generated by Django 5.2 on 2025-05-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_store',
            field=models.CharField(blank=True, choices=[('monkey_planet', 'Monkey Planet'), ('baul_del_enano', 'Baul del Enano'), ('dragonscave', 'Dragonscave'), ('camelot', 'Camelot'), ('tiempo_de_juegos', 'Tiempo de Juegos')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transaction_preference',
            field=models.CharField(blank=True, choices=[('buy_only', 'Solo Compra'), ('sell_only', 'Solo Venta'), ('buy_and_sell', 'Compra y Venta')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
