# Generated by Django 5.2 on 2025-05-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number_customuser_preferred_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='transaction_preference',
            field=models.CharField(blank=True, choices=[('sell_only', 'Solo Venta'), ('trade_only', 'Solo Cambio'), ('trade_and_sell', 'Cambio y Venta'), ('display_only', 'Solo Display')], default='trade_and_sell', max_length=20, null=True),
        ),
    ]
