# Generated by Django 5.2 on 2025-05-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_transaction_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exchange_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('trade', 'Cambio')], default='trade', max_length=10),
        ),
        migrations.AddField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=10),
        ),
    ]
