# Generated by Django 5.2.13 on 2026-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_exchange_exchange_type_exchange_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collector_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='eur_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='card',
            name='set_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='set_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='usd_foil_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='condition',
            field=models.CharField(choices=[('near_mint', 'Near Mint'), ('lightly_played', 'Lightly Played'), ('moderately_played', 'Moderately Played'), ('heavily_played', 'Heavily Played'), ('damaged', 'Damaged')], default='near_mint', max_length=24),
        ),
        migrations.AddField(
            model_name='usercard',
            name='listing_intent',
            field=models.CharField(choices=[('sell', 'Venta'), ('trade', 'Cambio'), ('sell_trade', 'Venta/Cambio')], default='trade', max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Informativo'), ('action', 'Accion'), ('error', 'Error')], default='info', max_length=10),
        ),
    ]
