# Generated by Django 5.2.13 on 2026-04-30 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_card_collector_number_card_eur_price_card_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_listing_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offered_cards_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_offers', to=settings.AUTH_USER_MODEL)),
                ('requested_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests', to='users.usercard')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('valuation_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offered_user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offer_items', to='users.usercard')),
                ('trade_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.tradeoffer')),
            ],
        ),
    ]
