# Generated by Django 5.2.13 on 2026-04-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tradeoffer_tradeofferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='desired_match_mode',
            field=models.CharField(choices=[('exact_printing', 'Solo esta version'), ('any_printing', 'Busco cualquier version')], default='exact_printing', max_length=20),
        ),
    ]
