# Generated by Django 5.2.13 on 2026-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usercard_desired_match_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'Sistema'), ('match', 'Match'), ('offer', 'Oferta'), ('trade', 'Intercambio')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
