# Generated by Django 5.2.13 on 2026-05-02 18:42

import django.db.models.deletion
from django.db import migrations, models


def seed_location_data(apps, schema_editor):
    City = apps.get_model('users', 'City')
    Store = apps.get_model('users', 'Store')

    for city_name in ['Quito', 'Machala', 'Guayaquil', 'Cuenca', 'Ambato']:
        City.objects.get_or_create(name=city_name, defaults={'is_active': True})

    store_rows = [
        ('monkey_planet', 'Monkey Planet', 'Quito'),
        ('baul_del_enano', 'Baul del Enano', 'Quito'),
        ('dragonscave', 'Dragonscave', 'Guayaquil'),
        ('camelot', 'Camelot', 'Guayaquil'),
        ('tiempo_de_juegos', 'Tiempo de Juegos', 'Cuenca'),
    ]
    for slug, name, city_name in store_rows:
        city, _ = City.objects.get_or_create(name=city_name, defaults={'is_active': True})
        Store.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'city': city,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_action_url_notification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Quito', max_length=80),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=180, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='users.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.RunPython(seed_location_data, migrations.RunPython.noop),
    ]
