# Generated by Django 5.2.13 on 2026-05-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_city_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='purchase_mode',
            field=models.CharField(choices=[('buy_now', 'Buy Now'), ('offer', 'Offer')], default='offer', max_length=16),
        ),
    ]
