# Generated by Django 5.2.13 on 2026-05-03 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_exchange_listing_target_card_agreed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('completed', 'Finalizado'), ('rejected', 'Rechazado')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('completed', 'Finalizado'), ('rejected', 'Rechazado')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='TransactionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.CharField(blank=True, default='', max_length=180)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.meetingagreement')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transaction_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_transaction_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reviewed_user', 'created_at'], name='users_trans_reviewe_71f0d2_idx'), models.Index(fields=['meeting', 'reviewer'], name='users_trans_meeting_88d32c_idx')],
                'unique_together': {('meeting', 'reviewer')},
            },
        ),
    ]
