# Generated by Django 5.2.13 on 2026-05-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_exchange_status_alter_tradeoffer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='inventory_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='inventory_settled',
            field=models.BooleanField(default=False),
        ),
    ]
