# filepath: /Users/usuario/Documents/Proyectos python/my_django_project/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import reject_offer, mark_all_resolved

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('marketplace/card/<int:card_id>/', views.marketplace_card_detail, name='marketplace_card_detail'),
    path('marketplace/listing/<int:listing_id>/buy/', views.sale_listing_detail, name='sale_listing_detail'),
    path('marketplace/listing/<int:listing_id>/trade/', views.initiate_trade, name='initiate_trade'),
    path('cards/', views.card_list, name='card_list'),
    path('inventory/', views.inventory_list, name='inventory_list'),
    path('wanted-inventory/', views.wanted_inventory_list, name='wanted_inventory_list'),
    path('add_card/<int:card_id>/<int:is_owned>/', views.add_card, name='add_card'),
    path('register/', views.register, name='register'),  # Ruta para el registro
    path('register_cards/', views.register_cards, name='register_cards'),  # Nueva ruta
    path('collection/<int:user_card_id>/edit/', views.edit_user_card, name='edit_user_card'),
    path('scryfall/search/', views.scryfall_card_search, name='scryfall_card_search'),
    path('search_card/', views.search_card, name='search_card'),
    path('delete_card/<int:card_id>/', views.delete_card, name='delete_card'),
    path('edit_card_quantity/<int:card_id>/', views.edit_card_quantity, name='edit_card_quantity'),
    path('search_card_matches/', views.search_card_matches, name='search_card_matches'),
    path('desired_match_mode/<int:user_card_id>/', views.update_desired_match_mode, name='update_desired_match_mode'),
    path('edit_profile/', views.edit_user_profile, name='edit_profile'),
    path('search_users_with_desired_card/', views.search_users_with_desired_card, name='search_users_with_desired_card'),
    path('view_user_cards/', views.view_user_cards, name='view_user_cards'),
    path('send_trade_request/', views.send_trade_request, name='send_trade_request'),
    path('send_notification/', views.send_notification, name='send_notification'),
    path('notifications/', views.list_notifications, name='list_notifications'),
    path('notifications/<int:notification_id>/resolve/', views.resolve_notification, name='resolve_notification'),
    path('offers/', views.active_ritual_offers, name='active_ritual_offers'),
    path('accept_notification/', views.accept_notification, name='accept_notification'),
    path('reject_notification/', views.reject_notification, name='reject_notification'),
    path('reject_offer/', reject_offer, name='reject_offer'),
    path('mark_all_resolved/', mark_all_resolved, name='mark_all_resolved'),
    path('create_card/', views.create_card, name='create_card'),
    path('user_info/<int:user_id>/', views.view_user_info, name='view_user_info'),
    path('exchanges/', views.list_exchanges, name='list_exchanges'),
    path('make_purchase_offer/', views.make_purchase_offer, name='make_purchase_offer'),
    path('pending_transactions/', views.pending_transactions, name='pending_transactions'),
    path('accept_exchange/<int:exchange_id>/', views.accept_exchange, name='accept_exchange'),
    path('reject_exchange/<int:exchange_id>/', views.reject_exchange, name='reject_exchange'),
    path('meeting/sale/<int:exchange_id>/', views.meeting_exchange, name='meeting_exchange'),
    path('meeting/trade/<int:offer_id>/', views.meeting_trade_offer, name='meeting_trade_offer'),
    path('trade_offer/<int:offer_id>/', views.trade_offer_review, name='trade_offer_review'),
    path('trade_offer/<int:offer_id>/accept/', views.accept_trade_offer, name='accept_trade_offer'),
    path('trade_offer/<int:offer_id>/reject/', views.reject_trade_offer, name='reject_trade_offer'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('bulk_lookup_chunk/', views.bulk_lookup_chunk, name='bulk_lookup_chunk'),
    path('import_cards/', views.import_cards, name='import_cards'),
    path('add_to_desired_cards/', views.create_user_cards_from_txt, name='add_to_desired_cards'),
    path('add_to_owned_cards/', views.add_to_owned_cards, name='add_to_owned_cards'),
]
